### ISSUE TITLE
Protecting webhook

### ISSUE THREAD

**Issue by shtoffeine** [joelwmale/webhook-action#10]
I use this package (https://github.com/adnanh/webhook) as webhook for server. It allows to protect webhook like this:
```
...
"match":
          {
            "type": "payload-hash-sha1",
            "secret": "<RANDOM-SECRET-STRING>",
            "parameter":
            {
              "source": "header",
              "name": "X-Hub-Signature"
            }
          }
...
```

where RANDOM-SECRET-STRING is secret key that can be used in Github Webhooks. Have feature for adding this header and secret key on this action?

**Comment by beshur** [comment]
You can just hide the secret in the repo secrets and use in the action as `${{ secrets.RANDOM_SECRET_STRING }}

See https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by schtoffen** [comment]
@beshur, I know about Github Secrets. You dont understand my question.

I ask how to add header to this action like it does Github Webhooks when calling hook:
`X-Hub-Signature: RANDOM-SECRET-STRING`

As I understand, this action does not support headers. Maybe @joelwmale will add this feature.

**Comment by beshur** [comment]
I see, sorry.

Actually, this action only does `curl` on your `WEBHOOK_URL` with `{data: $data}`, so you can as easily do it yourself, until the custom headers are supported.

**Comment by joelwmale** [comment]
Custom headers are now supported as of [v2.0.0](https://github.com/joelwmale/webhook-action/releases/tag/2.0.0). You could use these to add your signature with a custom string to protect your API.
