### ISSUE TITLE
Check for response status

### ISSUE THREAD

**Issue by AnandChowdhary** [joelwmale/webhook-action#22]
It'd be great if we could fail the status check if the server responds with a `40x` or `50x` status rather than an expected `20x` repsonse.

![Screen Shot 2020-08-28 at 16 48 20](https://user-images.githubusercontent.com/2841780/91555263-4a361280-e94e-11ea-9fd7-d2f737e0905d.png)

In this example, I had no way of knowing that this webhook was triggered but the server threw an error.

**Comment by joelwmale** [comment]
Your branch has been merged and released. Thanks again for your help on the project @AnandChowdhary!
