### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by devenes** [joelwmale/webhook-action#605]
As @depoulo mentioned https://github.com/joelwmale/webhook-action/issues/593#issuecomment-1309980721, we still face the warning,

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I was thinking that this error is due to env files as stated in the [document](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). I want to ask that should we consider to change `set-output` command;

https://github.com/joelwmale/webhook-action/blob/2c43ebbef8b9c5e5ea27cd65dfdeac58f90e7e29/dist/index.js#L334-L344

**Comment by joelwmale** [comment]
@depoulo let me try that now, one sec.

**Comment by joelwmale** [comment]
@devenes @depoulo try the latest release

**Comment by depoulo** [comment]
```
Could not find file '/home/runner/work/_actions/_temp_a65493dc-fe4f-4e98-90b4-43ce81cb38d3/_staging/joelwmale-webhook-action-29d4f52/node_modules/.bin/semver'.
```

**Comment by depoulo** [comment]
![grafik](https://user-images.githubusercontent.com/4457202/201075176-fa8224d0-07cd-4c38-a028-20c07391e9e0.png)

Looks like you need to add `semver` as a direct dependency.

**Comment by joelwmale** [comment]
Hmm this is strange, let me give that a go

**Comment by joelwmale** [comment]
Give that a go now @depoulo. Not sure why it's asking for semver..

**Comment by depoulo** [comment]
Currently trying out `depoulo/webhook-action@fix-dep-updates`…

**Comment by depoulo** [comment]
Which does not work either. Now trying out your 2.3.1 🤞🏽

**Comment by depoulo** [comment]
> Error: Cannot find module 'uuid'

I'd suggest trying this out on your own, or publishing only branches, not versions, until this is confirmed to have been fixed.

**Comment by joelwmale** [comment]
v2.3.2 fixes all issues relating to dependencies. Thanks guys.

**Comment by depoulo** [comment]
Thank you for the quick fix 🎉
