### ISSUE TITLE
Mimick github's webhook payload data

### ISSUE THREAD

**Issue by LecrisUT** [joelwmale/webhook-action#645]
Let's say there is a new commit pushed and you want github's webhook to be delayed until other CI jobs finish running. It would be nice in this situation to mimick github's payload for that event (or at least as much as possible). That way it can be plug-and-play replacement for the services that rely on webhook integration.

This could then be the default payloads to send.

**Comment by joelwmale** [comment]
@LecrisUT you can have this job run after other CI jobs by setting the needs variable of the job? See documentation here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds

I could look at getting the github payload event for whatever happened (i.e push, merge, etc), would that help?

**Comment by LecrisUT** [comment]
> I could look at getting the github payload event for whatever happened (i.e push, merge, etc), would that help?

Indeed that is exactly what I was trying to say in this issue.

**Comment by joelwmale** [comment]
@LecrisUT this has been added in v2.4.0: https://github.com/joelwmale/webhook-action/tree/master?tab=readme-ov-file#action-input
