### ISSUE TITLE
Make data optional

### ISSUE THREAD

**Issue by AnandChowdhary** [joelwmale/webhook-action#9]
Currently, in [entrypoint.sh#L4](https://github.com/joelwmale/webhook-action/blob/master/entrypoint.sh#L4), data is passed regardless of whether it exists as an environment variable. 

This results in the following error (https://github.com/Karuna2020/open-data/runs/575048122) in case only `WEBHOOK_URL` is available as an environment variable, not `data`:

```
/entrypoint.sh: 4: /entrypoint.sh: data: parameter not set
```

It would be nice if this wasn't thrown, and the POST request goes through without adding the body.

**Comment by joelwmale** [comment]
The body input is now optional as part of [v2.0.0](https://github.com/joelwmale/webhook-action/releases/tag/2.0.0)
